name: Deploy AWS CloudFormation terraform_state/stack

on: [push]
  # push:
  #   paths:
  #   - terraform_state

jobs:
  deploy:
    environment: latschesar-atanassov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-duration-seconds: 1200
      
      - name: Deploy AWS CloudFormation terraform_state/stack
        uses: aws-actions/aws-cloudformation-github-deploy@v1
        with:
          name: terrafromState
          template: terraform_state/stack.yml
