name: Deploy terraform state infrastructure

on: [push]
  # push:
  #   paths:
  #   - terraform_state

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::971776360507:role/gha_terraform_deployer